services:
  - type: web
    name: helpdesk-system
    env: python
    region: frankfurt
    repo: https://github.com/seyf-eddine19/helpdesk_system
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn helpdesk_system.wsgi:application --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: helpdesk-db
          property: connectionString
      - key: EMAIL_HOST
        value: "smtppro.zoho.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "aloola-helpdesk@zohomail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "aloola-helpdesk@zohomail.com"

databases:
  - name: helpdesk-db
    region: frankfurt
    plan: free
